name:                gen-rts-makefile
version:             0.1.0.0
github:              victorwallsten/gen-rts-makefile
license:             BSD3
author:              Victor Wallsten
maintainer:          victor.wallsten@protonmail.com
copyright:           2022 Victor Wallsten

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/victorwallsten/gen-rts-makefile#readme>

dependencies:
- base >= 4.11 && < 10

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  gen-rts-makefile-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - gen-rts-makefile

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
